name: flutter_application_1
description: "PawGuard - AI-Powered Animal Emergency Response"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0  

  cupertino_icons: ^1.0.8
  
  # Firebase - Core tools 
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  
  google_generative_ai: ^0.4.7

  # Camera/Gallery Tool - MUST HAVE for AI Vision analysis
  image_picker: ^1.0.4
  
  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pawalert logo.png" #
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"     
  adaptive_icon_foreground: "assets/images/pawalert logo.png"